apiVersion: v1
kind: Namespace
metadata:
  name: gitlab-runner
---
# needs input from salt state to put in the runner token
# should also be further configured once i get a better grasp on what is needed for the actual runners
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: gitlab-runner
  namespace: gitlab-runner
spec:
  chart: gitlab/gitlab-runner
  targetNamespace: gitlab-runner
  valuesContent: |-
    image:
      registry: registry.gitlab.com
      image: my-gitlab-runner
      tag: v1
    useTini: false
    imagePullPolicy: IfNotPresent
    livenessProbe: {}
    #   initialDelaySeconds: 60
    #   periodSeconds: 60
    #   successThreshold: 1
    #   failureThreshold: 3
    #   terminationGracePeriodSeconds: 30
    readinessProbe: {}
    #   initialDelaySeconds: 60
    #   periodSeconds: 60
    #   successThreshold: 1
    #   failureThreshold: 3
    # replicas: 1
    # revisionHistoryLimit: 10
    gitlabUrl: CONFIGURE_THE_URL
    runnerToken: "CONFIGURE_THE_TOKEN"
    unregisterRunners: true
    terminationGracePeriodSeconds: 3600
    # certsSecretName:
    concurrent: 10
    shutdown_timeout: 0
    checkInterval: 3
    # logLevel:
    # logFormat:
    # sentryDsn:
    # connectionMaxAge: "15m"
    #preEntrypointScript:
    ## ref:
    sessionServer:
      enabled: false
      # annotations: {}
      # timeout: 1800
      # internalPort: 8093
      # externalPort: 9000
      # nodePort: 30093
      # publicIP: ""
      # loadBalancerSourceRanges:
      #   - 1.2.3.4/32
      serviceType: LoadBalancer
      # externalTrafficPolicy:
      # internalTrafficPolicy:
      ingress:
        enabled: false
        className: ""
        annotations: {}
        tls:
          - secretName: gitlab-runner-session-server

    ## For RBAC support:
    rbac:
      create: true
      generatedServiceAccountName: ""
      rules:
        - resources: ["events"]
          verbs: ["list", "watch"]
        - resources: ["namespaces"]
          verbs: ["create", "delete"]
        - resources: ["pods"]
          verbs: ["create","delete","get"]
        - apiGroups: [""]
          resources: ["pods/attach","pods/exec"]
          verbs: ["get","create","patch","delete"]
        - apiGroups: [""]
          resources: ["pods/log"]
          verbs: ["get","list"]
        - resources: ["secrets"]
          verbs: ["create","delete","get","update"]
        - resources: ["serviceaccounts"]
          verbs: ["get"]
        - resources: ["services"]
          verbs: ["create","get"]
      clusterWideAccess: false
      # serviceAccountName: default
      serviceAccountAnnotations: {}
      podSecurityPolicy:
        enabled: false
        resourceNames:
          - gitlab-runner
      imagePullSecrets: []
    serviceAccount:
      create: true
      name: ""
      annotations: {}
      imagePullSecrets: []
    metrics:
      enabled: false
      portName: metrics
      port: 9252
      serviceMonitor:
        enabled: false
        namespace: ""
        ## labels: {}
        ## annotations: {}
        # interval: ""
        # scheme: "http"
        # tlsConfig: {}
        # path: "/metrics"
        # metricRelabelings: []
        ## relabelings: []
    service:
      enabled: false
      # labels: {}
      # annotations: {}
      # clusterIP: ""
      # externalIPs: []
      # loadBalancerIP: ""
      # loadBalancerSourceRanges: []
      type: ClusterIP
      # metrics:
      # nodePort: ""
      # additionalPorts: []
      # externalTrafficPolicy:
      # internalTrafficPolicy:
    runners:
      config: |
        [[runners]]
          [runners.kubernetes]
            namespace = "{{ default .Release.Namespace .Values.runners.jobNamespace }}"
            image = "alpine"
      configPath: ""
      # executor: kubernetes
      # name: ""
      # secret: gitlab-runner
      cache: {}
    # schedulerName: "my-custom-scheduler"
    securityContext:
      allowPrivilegeEscalation: false
      readOnlyRootFilesystem: false
      runAsNonRoot: true
      privileged: false
      capabilities:
        drop: ["ALL"]
    strategy: {}
    podSecurityContext:
      runAsUser: 100
      # runAsGroup: 65533
      fsGroup: 65533
      # supplementalGroups: [65533]

      ## Note: values for the ubuntu image:
      # runAsUser: 999
      # fsGroup: 999

    ## Configure resource requests and limits
    ## ref: https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/
    ##
    resources: {}
      # limits:
      #   memory: 256Mi
      #   cpu: 200m
      #   ephemeral-storage: 512Mi
      # requests:
      #   memory: 128Mi
      #   cpu: 100m
      #   ephemeral-storage: 256Mi

    ## Affinity for pod assignment
    ## ref: https://kubernetes.io/docs/concepts/configuration/assign-pod-node/#affinity-and-anti-affinity
    ##
    affinity: {}
    topologySpreadConstraints: {}
    runtimeClassName: ""
    nodeSelector: {}
    tolerations: []
    # envVars:
    extraEnv: {}
    extraEnvFrom: {}
    hostAliases: []
    deploymentAnnotations: {}
    deploymentLabels: {}
    deploymentLifecycle: {}
    #hostname: my-gitlab-runner
    podAnnotations: {}
    podLabels: {}
    priorityClassName: ""
    secrets: []
    configMaps: {}
    volumeMounts: []
    volumes: []
    extraObjects: []
    extraContainers: []